# Generated by Django 3.0.5 on 2020-11-25 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdealFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NeckType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sleeve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tshirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(default='', max_length=50)),
                ('description', models.CharField(max_length=50, null=True)),
                ('discount', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='upload/img/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tshirtapp.Brand')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tshirtapp.Color')),
                ('idealfor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tshirtapp.IdealFor')),
                ('necktype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tshirtapp.NeckType')),
                ('occasion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tshirtapp.Occasion')),
                ('sleeve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tshirtapp.Sleeve')),
            ],
        ),
        migrations.CreateModel(
            name='SizeVarient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('size', models.CharField(choices=[('S', 'SMALL'), ('M', 'MEDIUM')], max_length=4)),
                ('tshirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tshirtapp.Tshirt')),
            ],
        ),
    ]
