# Generated by Django 3.0.5 on 2020-11-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tshirtapp', '0002_auto_20201125_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirt',
            name='slug',
            field=models.CharField(default='', max_length=50, null=True, unique=True),
        ),
    ]
